spring:
  application:
    #应用名称
    name: SpringCloud-EurekaServer
eureka:
  instance:
    #声明以IP地址进行注册到服务中心
    prefer-ip-address: false
  client:
    #声明是否将自己的信息注册到Eureka服务器
    registerWithEureka: true
    #声明是否到Eureka服务器抓取注册信息
    fetch-registry: true
---
spring:
  profiles: peer1
server:
  #应用端口号
  port: 1111
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      #注册中心
      defaultZone: http://peer2:1112/eureka/
---
spring:
  profiles: peer2
server:
  #应用端口号
  port: 1112
eureka:
  instance: 
    hostname: peer2
  client:
    serviceUrl:
      #注册中心
      defaultZone: http://peer1:1111/eureka/
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      